### ISSUE TITLE
Assistance with Preparing chrom_sizes and Reference Files for HMMSTR

### ISSUE THREAD

**Issue by HLHsieh** [Boyle-Lab/HMMSTR#8]
Hi there,

I was excited to run HMMSTR with BAM files. However, I am unsure how to prepare my own chrom_sizes and reference files for execution. I would greatly appreciate it if you could provide sample code along with the corresponding files.

Thank you,
Hsin-Lun

**Comment by kvandeynze** [comment]
Hi Hsin-Lun,

Thanks for reaching out! The reference fasta file and chromosome sizes file for hg38 can be found in the UCSC genome browser downloads here: https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/ 

The reference is here [hg38.fa.gz](https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz)
and the chromosome sizes can be found here [hg38.chrom.sizes](https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.chrom.sizes)

If you are using an alternative reference genome, the same files should be available to download as well.

Please let me know if you have any further questions,
Kinsey
